### ISSUE TITLE
仍然保留对实验的疑问

### ISSUE THREAD

**Issue by nnstake** [ForestsKing/GLAFF#4]
既然都是国人我就打中文了。我知道你们是重写了实验代码，但是我并不理解这个行为，过去两年的领域实验基本沿用一套代码逻辑，实验结果也是能很清晰的比较。在这种情况下，为何要写一套新的代码，这套代码的数据处理合理吗，这些都是可能引发的问题。此外，文中在4.1强调了实验设置和结果都是按照已有的论文规范来的，附录A.1也是笼统地介绍数据集，并没有关于你们的实验设置和别人的不同之处，因此引起的我的关注是很正常的，至于审稿人，大概率是不会注意到这么深的实验问题（当然这并不代表我在质疑你们的数据有什么问题。此外，对于你们的这套代码框架，我简单扫一下就发现了一个不合理之处，就是在MyDataset中对于数据的标准化处理，机器学习领域正常的处理方式都是对训练集fit，然后对全部数据transform，但是你们的处理中直接对整个数据fit，这显然不合理，对测试集带来了信息泄露的问题。最后，在这套框架下你是否对使用的baseline进行了调参呢？原论文中必然是经过了模型调优的结果，但是迁移到你的框架下是否调参了呢，这会不会就是baseline跑得低的部分原因呢？

**Comment by nnstake** [comment]
此外，在代码库中给定的run.sh的实验中，关于iTransformer在traffic的实验，默认的10个epoch设置下，baseline都还没收敛呢，20个epoch跑完都还没earlystopping，是否说明了给定的实验结果不够充分？

**Comment by ForestsKing** [comment]
Thank you for your interest in our work. The standardized processing code you mentioned indeed poses a risk of information leakage, which we will address in a future version. We appreciate your attention to this matter.

Nonetheless, we believe a robust algorithm should adapt well to slight data drift, particularly in minor shifts of basic statistics such as mean and variance. For models employing instance normalization, like TimesNet and iTransformer, small variations in dataset mean and variance have minimal impact on model convergence. Therefore, despite the information leakage issue, we believe it does not substantially affect the relative performance across different models within the same dataset, and our experimental findings remain compelling. Additionally, our algorithm prioritizes the enhancement of various backbones within the same experimental framework over absolute performance metrics.

Our choice to use a new code framework is primarily due to personal preference and project requirements. While the existing code is widely adopted, writing each function according to our own practices better serves specific research needs and enhances code readability and maintainability. We apologize if this has caused any confusion.

Regarding the experimental settings for iTransformer on the traffic dataset, we acknowledge that the default 10 epochs may not be sufficient for full model convergence. This is a valuable observation, and we recognize that in some cases, increasing the training rounds could improve model performance. However, our focus was on comparing the relative performance of various methods under consistent experimental conditions rather than achieving the optimal performance for a single model. You may also consider sharing this observation with [iTransformer](https://github.com/thuml/iTransformer) and [Time-Series-Library](https://github.com/thuml/Time-Series-Library), as they utilize similar epoch settings in their predictions.
